crm/urls.py
# -*- coding: utf-8 -*-


"""crm URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import setting_street.urls
import extuser.urls
import homes.urls
import notes.urls
import facility.urls
import setting_globall.urls
import trash_object.urls
import single_object.urls
import who_online.urls
import send_messege_user.urls
import arendator.urls
import buyer.urls
import makler.urls
import setting_superadmin.urls
import tasking.urls
import parsings.urls
import posting.urls
import watermark.urls
import sender_email.urls
import setting_mail_delivery.urls
import meeting.urls
import searching.urls
import single_arendator.urls
import single_buyer.urls
import backupbd_crm.urls
import learning.urls
import access.urls

urlpatterns = [
    url(r'^', include(setting_street.urls)),
    url(r'^', include(extuser.urls)),
    url(r'^', include(homes.urls)),
    url(r'^', include(notes.urls)),
    url(r'^objects/', include(facility.urls)),
    url(r'^', include(setting_globall.urls)),
    url(r'^', include(trash_object.urls)),
    url(r'^objects/', include(single_object.urls)),
    url(r'^', include(who_online.urls)),
    url(r'^', include(send_messege_user.urls)),
    url(r'^arendators/', include(arendator.urls)),
    url(r'^buyers/', include(buyer.urls)),
    url(r'^', include(makler.urls)),
    url(r'^', include(setting_superadmin.urls)),
    url(r'^tasking/', include(tasking.urls)),
    url(r'^', include(parsings.urls)),
    url(r'^', include(posting.urls)),
    url(r'^', include(watermark.urls)),
    url(r'^', include(sender_email.urls)),
    url(r'^', include(setting_mail_delivery.urls)),
    url(r'^', include(meeting.urls)),
    url(r'^', include(searching.urls)),
    url(r'^arendators/', include(single_arendator.urls)),
    url(r'^buyers/', include(single_buyer.urls)),
    url(r'^', include(backupbd_crm.urls)),
    url(r'^', include(learning.urls)),
    url(r'^', include(access.urls)),
    # admin
    url(r'^admin/', admin.site.urls),
    # end admin
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

makler/urls.py
# -*- coding: utf-8 -*-


from django.conf.urls import url
from makler.views import add_makler, form_makler, edit_makler, save_edit_makler, MaklerListWhite, MaklerListBlack, \
    search_makler, del_makler


urlpatterns = [
    url(r'add_makler$', add_makler, name='add_makler'),
    url(r'form_makler$', form_makler, name='form_makler'),
    url(r'edit_makler$', edit_makler, name='edit_makler'),
    url(r'del_makler$', del_makler, name='del_makler'),
    url(r'maklers_white$', MaklerListWhite.as_view(), name='maklers_white'),
    url(r'^maklers_black$', MaklerListBlack.as_view(), name='maklers_black'),
    url(r'^search_makler$', search_makler, name='search_makler'),
    url(r'save_edit_makler/(?P<id>[0-9]+)$', save_edit_makler, name='save_edit_makler'),
]

settings_domen/urls.py
# -*- coding: utf-8 -*-


"""crm URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import setting_street.urls
import extuser.urls
import homes.urls
import notes.urls
import facility.urls
import setting_globall.urls
import trash_object.urls
import single_object.urls
import who_online.urls
import send_messege_user.urls
import arendator.urls
import buyer.urls
import makler.urls
import setting_superadmin.urls
import tasking.urls
import parsings.urls
import posting.urls
import watermark.urls
import sender_email.urls
import setting_mail_delivery.urls
import meeting.urls
import searching.urls
import single_arendator.urls
import single_buyer.urls
import backupbd_crm.urls
import learning.urls

urlpatterns = [
    url(r'^', include(setting_street.urls)),
    url(r'^', include(extuser.urls)),
    url(r'^', include(homes.urls)),
    url(r'^', include(notes.urls)),
    url(r'^objects/', include(facility.urls)),
    url(r'^', include(setting_globall.urls)),
    url(r'^', include(trash_object.urls)),
    url(r'^objects/', include(single_object.urls)),
    url(r'^', include(who_online.urls)),
    url(r'^', include(send_messege_user.urls)),
    url(r'^arendators/', include(arendator.urls)),
    url(r'^buyers/', include(buyer.urls)),
    url(r'^maklers/', include(makler.urls)),
    url(r'^', include(setting_superadmin.urls)),
    url(r'^tasking/', include(tasking.urls)),
    url(r'^', include(parsings.urls)),
    url(r'^', include(posting.urls)),
    url(r'^', include(watermark.urls)),
    url(r'^', include(sender_email.urls)),
    url(r'^', include(setting_mail_delivery.urls)),
    url(r'^', include(meeting.urls)),
    url(r'^', include(searching.urls)),
    url(r'^arendators/', include(single_arendator.urls)),
    url(r'^buyers/', include(single_buyer.urls)),
    url(r'^', include(backupbd_crm.urls)),
    url(r'^', include(learning.urls)),
    # admin
    url(r'^admin/', admin.site.urls),
    # end admin
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

makler/models.py
# -*- coding: utf-8 -*-


from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserFullName(User):
    class Meta:
        proxy = True

    def __unicode__(self):
        return self.get_full_name()


class TypeCooperations(models.Model):
    class Meta(object):
        verbose_name = u'Тип сотрудничества'
        verbose_name_plural = u'Типи сотрудничества'

    type_cooperation = models.CharField(max_length=50, verbose_name=u'Тип сотрудничества')

    def __unicode__(self):
        return '%s' % self.type_cooperation


class TypeWhiteBlack(models.Model):
    class Meta(object):
        verbose_name = u'Тип маклера'
        verbose_name_plural = u'Типи маклеров'

    type_white_black = models.CharField(max_length=50, verbose_name=u'Тип маклера')

    def __unicode__(self):
        return '%s' % self.type_white_black


class Makler(models.Model):
    class Meta(object):
        verbose_name = u'Маклер'
        verbose_name_plural = u'Маклера'

    name = models.CharField(max_length=30, verbose_name=u'Имя', blank=True, null=True)

    agency = models.CharField(max_length=30, verbose_name=u'Агенство', blank=True, null=True)

    white_black = models.ForeignKey(TypeWhiteBlack,
                                    verbose_name=u'Тип маклера',
                                    blank=False,
                                    null=False,
                                    on_delete=models.PROTECT)

    phone = models.CharField(max_length=15, verbose_name=u'Телефон', blank=False, null=True)

    phone_second = models.CharField(max_length=15, verbose_name=u'Телефон 2', blank=True, null=True)

    phone_third = models.CharField(max_length=15, verbose_name=u'Телефон 3', blank=True, null=True)

    site = models.URLField(verbose_name=u'Сайт', null=True, blank=True)

    email = models.EmailField(verbose_name=u'Email', null=True, blank=True)

    cooperation = models.ForeignKey(TypeCooperations,
                                    verbose_name=u'Тип сотрудничества',
                                    blank=True,
                                    null=True,
                                    on_delete=models.PROTECT)

    rieltor = models.ForeignKey(UserFullName,
                                blank=True,
                                null=True,
                                verbose_name=u'Риелтор',
                                on_delete=models.PROTECT)

    add_date = models.DateTimeField(verbose_name=u'Дата добавления', auto_now_add=True)

    def __unicode__(self):
        return '%s' % self.id

makler/forms.py
# -*- coding: utf-8 -*-


from django.forms import ModelForm, TextInput, Select, SelectMultiple
from makler.models import Makler


class MaklerForm(ModelForm):
    class Meta:
        model = Makler
        fields = ('name', 'agency', 'cooperation', 'email', 'phone', 'phone_second', 'phone_third', 'site', 'white_black', 'rieltor')
        widgets = {
            'phone': TextInput(attrs={}),
            'email': TextInput(attrs={}),
            'site': TextInput(attrs={}),
            'white_black': Select(attrs={'style': 'min-width: 100%'}),
            'cooperation': Select(attrs={'style': 'min-width: 100%'}),
            'rieltor': Select(attrs={'style': 'min-width: 100%'}),
        }

makler/views.py
# -*- coding: utf-8 -*-


from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from makler.forms import MaklerForm
from makler.models import Makler, TypeCooperations, UserFullName
from homes.views import MaklerList
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.db.models import Q

# Create your views here.


class MaklerListWhite(MaklerList):
    qeryset = Makler.objects.filter(white_black=1)

    def get_queryset(self):
        return self.qeryset

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(MaklerListWhite, self).dispatch(request, *args, **kwargs)


class MaklerListBlack(MaklerList):
    qeryset = Makler.objects.filter(white_black=2)

    def get_queryset(self):
        return self.qeryset

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(MaklerListBlack, self).dispatch(request, *args, **kwargs)


@login_required
def search_makler(request):
    if request.method == 'POST':
        queryset = Makler.objects.all().order_by('id')
        if request.POST.get('search_makler_number'):
            search_phone = request.POST.get('search_makler_number')
            queryset = queryset.filter(Q(phone__icontains=search_phone) | Q(
                phone_second__icontains=search_phone) | Q(phone_third__icontains=search_phone))
        if (request.POST.get('search_cooperation')).isdigit():
            type_coop = TypeCooperations.objects.filter(id=request.POST.get('search_cooperation'))
            queryset = queryset.filter(cooperation=type_coop)
        return render(request, 'makler/list_makler.html', {"maklers": queryset})


@login_required
def add_makler(request):
    if request.method == 'POST':
        form = MaklerForm(request.POST)
        if form.is_valid():
            form.save()
            post = Makler.objects.last()
            return render(request, 'makler/single_makler.html', {"makler": post})
        else:
            # form = change_form_text(form)
            form = MaklerForm(request.POST)
        return form_makler(request, form)
    else:
        return HttpResponse(status=404)


@login_required
def form_makler(request, form=MaklerForm()):
    form.fields['rieltor'].queryset = UserFullName.objects.filter(is_active=True)
    if form.errors:
        return render(request, 'makler/form.html', {"form": form}, status=404)
    return render(request, 'makler/form.html', {"form": form})


@login_required
def edit_makler(request):
    if request.method == 'POST':
        post = get_object_or_404(Makler, pk=request.POST.get('id'))
        form = MaklerForm(instance=post)
        form.fields['rieltor'].queryset = UserFullName.objects.filter(is_active=True)
        return render(request, 'makler/edit_makler.html', {"form": form, "id_makler": post})
    else:
        return HttpResponse(status=404)


@login_required
def save_edit_makler(request, id):
    if request.method == 'POST':
        post = get_object_or_404(Makler, pk=id)
        form = MaklerForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return render(request, 'makler/single_makler.html', {"makler": post})
        else:
            form = MaklerForm(request.POST, instance=post)
            return render(request, 'makler/edit_makler.html', {"form": form, "id_makler": post}, status=404)
    else:
        return HttpResponse(status=404)


@login_required
def del_makler(request):
    if request.method == 'POST':
        try:
            Makler.objects.get(id=request.POST.get('id')).delete()
        except:
            return HttpResponse(status=500)
        return HttpResponse(content=b'Успешно удалено', status=200)

makler/templates/makler/edit_makler.html
 <div class="makler-form container">
        <div class="row">
            <div class="col-md-12">
                <form id="send_form" action="makler/add_makler" method="post">
                {% csrf_token %}
                    <h3 style="padding-left: 20px" class="section-head">Добавить маклера</h3>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="name">Имя</label>
                            {{ form.name }}
                        </div>
                        <div class="col-md-6">
                            <label for="name-agency">Название Агенства</label>
                            {{ form.agency }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="white">Тип маклера</label>
                            {% if form.white_black.errors %}
                                <span style="color: #cc0000">{{ form.white_black.errors.as_text }}</span>
                            {% endif %}
                            {{ form.white_black }}
                        </div>
                        <div class="col-md-6">
                            <label for="phone">Телефон
                                {% if form.phone.errors %}
                                    <span style="color: #cc0000"> {{ form.phone.errors.as_text }} </span>
                                {% endif %}
                                </label>
                                {{ form.phone }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="phone">Телефон 2
                                {% if form.phone_second.errors %}
                                    <span style="color: #cc0000"> {{ form.phone_second.errors.as_text }} </span>
                                {% endif %}
                                </label>
                                {{ form.phone_second }}
                        </div>
                        <div class="col-md-6">
                            <label for="phone">Телефон 3
                                {% if form.phone_third.errors %}
                                    <span style="color: #cc0000"> {{ form.phone_third.errors.as_text }} </span>
                                {% endif %}
                                </label>
                                {{ form.phone_third }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="site">Сайт</label>
                            {% if form.site.errors.as_text %}
                                    <span style="color: #cc0000"> {{ form.site.errors.as_text }} </span>
                            {% endif %}
                            {{ form.site }}
                        </div>
                        <div class="col-md-6">
                            <label for="email">Email
                                {% if form.email.errors.as_text %}
                                    <span style="color: #cc0000"> {{ form.email.errors.as_text }} </span>
                                {% endif %}
                            </label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="cooperation">Сотрудничество</label>
                            {{ form.cooperation }}
                        </div>
                        <div class="col-md-6">
                            <label for="rieltor">Риелтор</label>
                            {{ form.email.rieltor.as_text }}
                            {{ form.rieltor }}
                        </div>
                    </div>
                    <br>
                    <br>
                    <br>
                    </form>
                    <div class="row">
                        <div class="col-md-6"><a id-makler-btn="{{ id_makler }}" id="edit_form_makler" class="btn btn-green" href="">Сохранить</a></div>
{#                        <div class="col-md-6"><input class="btn btn-green" type="submit"></div>#}
                            <div class="col-md-6" style="text-align: right;"><a id="cancel_add_makler" class="btn btn-red" href="">Отменить</a></div>
                    </div>

            </div>
        </div>
    </div>

<script type="text/javascript">
    $('#id_phone').change(function(event) {
        if (this.value.match(/[^0-9\.\+]/g)) {
            this.value = this.value.replace(/[^0-9\.\+]/g, '');
        }
    });
</script>

makler/templates/makler/form.html
 <div class="makler-form container">
        <div class="row">
            <div class="col-md-12">
                <form id="send_form" action="makler/add_makler" method="post">
                {% csrf_token %}
                    <h3 style="padding-left: 20px" class="section-head">Добавить маклера</h3>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="name">Имя</label>
                            {{ form.name }}
                        </div>
                        <div class="col-md-6">
                            <label for="name-agency">Название Агенства</label>
                            {{ form.agency }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="white">Тип маклера</label>
                            {% if form.white_black.errors %}
                                <span style="color: #cc0000">{{ form.white_black.errors.as_text }}</span>
                            {% endif %}
                            {{ form.white_black }}
                        </div>
                        <div class="col-md-6">
                            <label for="phone">Телефон
                                {% if form.phone.errors %}
                                    <span style="color: #cc0000"> {{ form.phone.errors.as_text }} </span>
                                {% endif %}
                                </label>
                                {{ form.phone }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="phone">Телефон 2
                                {% if form.phone_second.errors %}
                                    <span style="color: #cc0000"> {{ form.phone_second.errors.as_text }} </span>
                                {% endif %}
                                </label>
                                {{ form.phone_second }}
                        </div>
                        <div class="col-md-6">
                            <label for="phone">Телефон 3
                                {% if form.phone_third.errors %}
                                    <span style="color: #cc0000"> {{ form.phone_third.errors.as_text }} </span>
                                {% endif %}
                                </label>
                                {{ form.phone_third }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="site">Сайт</label>
                            {% if form.site.errors.as_text %}
                                    <span style="color: #cc0000"> {{ form.site.errors.as_text }} </span>
                            {% endif %}
                            {{ form.site }}
                        </div>
                        <div class="col-md-6">
                            <label for="email">Email
                                {% if form.email.errors.as_text %}
                                    <span style="color: #cc0000"> {{ form.email.errors.as_text }} </span>
                                {% endif %}
                            </label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="cooperation">Сотрудничество</label>
                            {{ form.cooperation }}
                        </div>
                        <div class="col-md-6">
                            <label for="rieltor">Риелтор</label>
                            {{ form.email.rieltor.as_text }}
                            {{ form.rieltor }}
                        </div>
                    </div>
                    <br>
                    <br>
                    <br>
                    </form>
                    <div class="row">
                        <div class="col-md-6"><a id="send_form_makler" class="btn btn-green" href="">Добавить</a></div>
{#                        <div class="col-md-6"><input class="btn btn-green" type="submit"></div>#}
                            <div class="col-md-6" style="text-align: right;"><a id="cancel_add_makler" class="btn btn-red" href="">Отменить</a></div>
                    </div>

            </div>
        </div>
    </div>

<script type="text/javascript">
    $('#id_phone').change(function(event) {
        if (this.value.match(/[^0-9\.\+]/g)) {
            this.value = this.value.replace(/[^0-9\.\+]/g, '');
        }
    });
    $('#id_phone_second').change(function(event) {
        if (this.value.match(/[^0-9\.\+]/g)) {
            this.value = this.value.replace(/[^0-9\.\+]/g, '');
        }
    });
    $('#id_phone_third').change(function(event) {
        if (this.value.match(/[^0-9\.\+]/g)) {
            this.value = this.value.replace(/[^0-9\.\+]/g, '');
        }
    });
</script>

makler/templates/makler/list_makler.html
{% for makler in maklers %}
    {% include 'makler/single_makler.html' %}
{% endfor %}

makler/templates/makler/single_makler.html
<tr>
    <td class="f-clr-grey">
        {{ makler.id }}
    </td>
    <td class="f-clr-grey">
        {% if makler.cooperation %}
            {{ makler.cooperation }} 
        {% endif %}
        <span class="makler-type makler-white">
        {% if makler.white_black.id == 1 %}
            <span class="makler-type makler-white">
        {% elif makler.white_black.id == 2 %}
        <span class="makler-type makler-black">
        {% else %}
        {% endif %}
        {{ makler.white_black }}
        </span>
    </td>
    <td class="f-clr-grey">
        <i class="fa fa-user"></i>
        {{ makler.name }}
    </td>
    <td class="f-clr-grey">
        #1
        <i class="fa fa-phone"></i>
        {{ makler.phone }}
        {% if makler.phone_second %}
            <br>
            #2
            <i class="fa fa-phone"></i>
            {{ makler.phone_second }}
        {% endif %}
        {% if makler.phone_third %}
            <br>
            #3
            <i class="fa fa-phone"></i>
            {{ makler.phone_third }}
        {% endif %}
    </td>
    <td class="f-clr-grey">
        {{ makler.agency }}
    </td>
    <td class="f-clr-grey">
        {{ makler.email }}
    </td>
        <td class="edit f-clr-grey">
            <a id-makler="{{ makler.id }}" href="#">
                <i class="fa fa-pencil"></i>
            </a>
            <a href="#">
                <i class="fa fa-times"></i>
            </a>
    </td>
    </tr>